---
title: "Untitled"
date: "2023-03-30"
editor_options: 
  chunk_output_type: console
output:
  bookdown::html_document2:
    toc: true
  pdf_document: 
    toc: true
always_allow_html: true
params:
  dataxx: NULL
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}

Diffthreshold <- 1
FDRthreshold <- 0.1

library(crosstalk)
library(prolfqua)
library(prolfquapp)
library(ggplot2)


#datax <- readr::read_tsv(, file = "datax.tsv" )
datax <- params$dataxx

bb <- datax |> dplyr::select(
  dplyr::all_of(
    c("protein_Id",
      "description",
      "contrast",
      "modelName",
      "diff",
      "FDR" )))

bb <- crosstalk::SharedData$new(bb, key = ~ protein_Id, group = "BB")

dt <- DT::datatable(
  bb, filter = "bottom",
  extensions = "Scroller",
  style = "auto",
  class = "compact",
  options = list(deferRender = TRUE,
                 scrollY = 300,
                 scrollX = 400,
                 scroller = TRUE) ) |>
  DT::formatRound(columns = c('FDR', 'diff'), digits = 3)


palette <- c("black","orange")
palette <- setNames(palette, c("Linear_Model_moderated", "Imputed_Mean_moderated"))

xd <- prolfqua::volcano_plotly(
  datax ,
  proteinID = "protein_Id",
  effect = "diff",
  significance = "FDR",
  contrast = "contrast",
  color = "modelName",
  palette = palette,
  xintercept =  c(-Diffthreshold,Diffthreshold),
  yintercept = FDRthreshold,
  title_size = 10,
  group = "BB")

xd <- lapply(xd, plotly::highlight , off = "plotly_doubleclick")
nrow <- ceiling(length(xd) / 4)

```

```{r}
dt
```

```{r}
plotly::subplot(xd, shareX = TRUE, shareY = TRUE, nrows = nrow)
```

```{r}

Diffthreshold <- 0
mx <- datax |> dplyr::mutate(passes = FDR < FDRthreshold)
mx <- mx |> dplyr::filter( passes )

ctdata <- mx |> dplyr::select(all_of(c("protein_Id" ,  "description", "contrast", "modelName", "diff", "FDR"  )))
sig <- crosstalk::SharedData$new(ctdata, ~protein_Id, group = "BB")
DT::datatable(sig,
              filter = "bottom",
              extensions = "Scroller",
              style = "auto",
              class = "compact",
              options = list(deferRender = TRUE,
                             scrollY = 300,
                             scrollX = 400,
                             scroller = TRUE) ) |>
  DT::formatRound(columns = c('FDR', 'diff'), digits = 3)

```



